import type { Article } from "@/types/article";

// 这里先放女子足球假新闻，用来把新闻页的布局、图片和信息层次搭起来。
export const mockArticles: Article[] = [
  {
    id: "wsl-1",
    title: "切尔西女足主场逆转获胜，锋线组合连线制造三球",
    summary: "一场高强度的英女超焦点战，展示了边路推进与二点球争夺的价值。",
    content: "切尔西女足在主场通过连续压迫和快速转换拿到优势。比赛后半段，前场三人组的协同跑位明显改善了进攻效率。",
    type: "news",
    coverUrl: "https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2026-08-27T10:00:00.000Z",
    authorName: "HerPitches 编辑部",
    isPinned: true,
    commentsCount: 32,
    reactionsCount: 126,
    relations: [{ teamId: "140224", teamName: "Chelsea Women" }],
  },
  {
    id: "wsl-2",
    title: "阿森纳女足的中场控制力为何会决定整场比赛节奏",
    summary: "从站位、传接球角度和压迫强度看，球队的控场能力正在回升。",
    content: "阿森纳女足通过更稳定的三角接应和更靠前的中场拦截，把比赛拖入自己擅长的节奏。",
    type: "feature",
    coverUrl: "https://images.unsplash.com/photo-1552667466-07770ae11077?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2026-08-26T14:30:00.000Z",
    authorName: "战术观察",
    commentsCount: 18,
    reactionsCount: 88,
    relations: [{ teamId: "140219", teamName: "Arsenal WFC" }],
  },
  {
    id: "wsl-3",
    title: "主力前锋伤愈回归，球队轮换方案将重新调整",
    summary: "球员状态恢复后，球队可能会在锋线和边路角色上重新分配任务。",
    content: "这篇人物内容聚焦球员的训练恢复、比赛节奏和球队阵容的重新搭配。",
    type: "profile",
    coverUrl: "https://images.unsplash.com/photo-1508083396222-5a1dc8b1f2f0?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2026-08-25T08:15:00.000Z",
    authorName: "人物线",
    commentsCount: 12,
    reactionsCount: 54,
    relations: [{ playerId: "mock-player-1", playerName: "Demo Player", teamId: "mock-arsenal-women", teamName: "Arsenal Women" }],
  },
  {
    id: "wsl-4",
    title: "战术板：高位压迫与边后卫前插如何影响比赛走向",
    summary: "用图文方式解释双边路推进、反抢和禁区二次进攻的配合。",
    content: "这是一篇战术内容示例，后续可以替换为真实比赛复盘。当前用于验证正文排版、图片比例和关联入口。",
    type: "tactics",
    coverUrl: "https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=900&q=80",
    publishedAt: "2026-08-24T19:40:00.000Z",
    authorName: "战术组",
    reactionsCount: 76,
    relations: [{ matchId: "mock-match-1", matchLabel: "示例比赛" }],
  },
];
